pipeline {
  agent none
  options {
    ansiColor('xterm')
  }
  stages {
    stage("Init title") {
      when {
        changeRequest()
        beforeAgent true
      }
      steps {
        script {
          currentBuild.displayName = "PR ${env.CHANGE_ID}: ${env.CHANGE_TITLE}"
        }
      }
    }
    stage('Build and Test') {
      agent {
        dockerfile { dir "jenkins" }
      }
      when {
        changeRequest()
        beforeAgent true
      }
      stages {
        stage('Build Solidity') {
          steps {
            sh '''
              make solc-compile
            '''
          }
        }
        stage('Install Firefly') {
          steps {
            sh '''
              ./install-firefly.sh ubuntu-bionic
            '''
          }
        }
      }
    }
  }
}
